import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Bot, CalendarClock, CheckCircle2, CircleAlert, Clock3, FileText, Landmark, Loader2, ShieldCheck, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { SetupRequired, date, label, money, riskStyle } from "./ReceivablesDashboard";

export default function InvoiceDetail({ params }: { params: { invoiceId: string } }) {
  const detail = trpc.invoices.detail.useQuery({ invoiceId: params.invoiceId });
  const ai = trpc.invoices.geminiAnalysis.useMutation();
  const simulation = trpc.invoices.simulate.useMutation();
  const utils = trpc.useUtils();
  const [promisedAmount, setPromisedAmount] = useState("");
  const [promisedDate, setPromisedDate] = useState("");
  const invoice = detail.data?.invoice;
  const candidateByAction = useMemo(() => new Map(detail.data?.intelligence?.candidates.map(candidate => [candidate.action, candidate]) ?? []), [detail.data?.intelligence?.candidates]);
  const runSimulation = (action: "send_reminder" | "follow_up" | "escalate" | "mark_promise_to_pay" | "do_nothing") => {
    if (!invoice || simulation.isPending) return;
    const promise = action === "mark_promise_to_pay" ? { promisedAmount: Number(promisedAmount), promisedDate } : undefined;
    simulation.mutate({ invoiceId: invoice.id, action, promise }, { onSuccess: () => { void utils.invoices.detail.invalidate({ invoiceId: invoice.id }); void utils.invoices.dashboard.invalidate(); void utils.invoices.promises.invalidate(); } });
  };
  if (detail.isLoading) return <div className="space-y-5"><Skeleton className="h-8 w-44" /><Skeleton className="h-44 rounded-2xl" /><Skeleton className="h-80 rounded-2xl" /></div>;
  if (detail.data?.setupRequired) return <div className="mx-auto max-w-7xl space-y-5 pb-10"><Link href="/invoices"><Button variant="ghost" className="-ml-3 rounded-lg text-slate-600"><ArrowLeft className="mr-2 h-4 w-4" />Back to invoices</Button></Link><SetupRequired message={"message" in detail.data ? detail.data.message : undefined} /></div>;
  if (detail.error || !invoice || !detail.data?.intelligence) return <section className="rr-surface mx-auto max-w-7xl p-8"><CircleAlert className="h-8 w-8 text-rose-500" /><h1 className="mt-4 text-2xl font-semibold text-slate-900">Invoice not found</h1><p className="mt-2 text-sm text-slate-500">This invoice is not present in the approved receivables source.</p><Link href="/invoices"><Button className="mt-5 rounded-lg bg-slate-900 text-white">Back to invoices</Button></Link></section>;
  const intelligence = detail.data.intelligence;
  return <div className="mx-auto max-w-7xl space-y-5 pb-10">{invoice.isSimulationDemo ? <section className="rounded-xl border border-violet-100 bg-violet-50 px-4 py-3 text-sm leading-6 text-violet-900"><span className="font-bold">Simulation demonstration record.</span> This <code>DEMO-</code> invoice and its related policy, action, promise, and audit entries are presentation data. No customer communication, payment, or source-invoice update can occur.</section> : null}<Link href="/invoices"><Button variant="ghost" className="-ml-3 rounded-lg text-slate-600 hover:bg-slate-100"><ArrowLeft className="mr-2 h-4 w-4" />Back to invoices</Button></Link>
    <section className="rr-surface border-l-4 border-l-teal-500 p-6 sm:p-7"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-sm font-semibold text-slate-800">{invoice.id}</p><Badge variant="outline" className="border-slate-200 bg-white text-slate-600">{label(invoice.status)}</Badge>{invoice.daysOverdue > 0 ? <Badge variant="outline" className="border-amber-100 bg-amber-50 text-amber-800">{invoice.daysOverdue} days overdue</Badge> : null}</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-slate-950">{money(invoice.outstandingAmount)} <span className="text-slate-400">outstanding</span></h1><p className="mt-2 text-sm text-slate-500">{invoice.customerName ?? invoice.customerId} · Due {date(invoice.dueDate)} · Issued {date(invoice.issuedDate)}</p><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => ai.mutate({ invoiceId: invoice.id })} disabled={ai.isPending || invoice.daysOverdue === 0} className="rounded-lg bg-violet-600 text-white hover:bg-violet-700">{ai.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Analysing…</> : <><Sparkles className="mr-2 h-4 w-4" />Analyze overdue invoice</>}</Button><Link href="/invoices/promises"><Button variant="outline" className="rounded-lg border-teal-200 bg-white text-teal-800 hover:bg-teal-50"><CalendarClock className="mr-2 h-4 w-4" />View promises</Button></Link></div></div><div className={`rounded-xl border px-4 py-3 ${riskStyle(intelligence.recoveryRisk)}`}><p className="text-[10px] font-bold uppercase tracking-[.14em] opacity-80">Calculated recovery risk</p><p className="mt-1 text-3xl font-semibold tracking-[-.05em]">{Math.round(intelligence.recoveryProbability * 100)}%</p><p className="mt-1 text-xs">{label(intelligence.recoveryRisk)} recovery opportunity · policy remains authoritative</p></div></div></section>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="rr-surface p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="rr-eyebrow">Deterministic receivables policy</p><h2 className="mt-1 text-xl font-semibold tracking-[-.04em] text-slate-950">Recommended action: {label(intelligence.recommendedAction)}</h2></div><ShieldCheck className="h-5 w-5 text-teal-600" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-teal-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-teal-700">Expected recovery value</p><p className="mt-1 text-xl font-semibold tracking-[-.04em] text-teal-900">{money(intelligence.expectedRecoveryValue)}</p><p className="mt-1 text-xs text-teal-700">Probability-weighted simulation estimate</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Decision factors</p><div className="mt-2 space-y-1.5">{intelligence.reasons.map(reason => <p key={reason} className="text-xs leading-5 text-slate-600">{reason}</p>)}</div></div></div><div className="mt-5 space-y-2">{intelligence.candidates.filter(candidate => candidate.action !== "mark_promise_to_pay").map(candidate => <div className="rounded-xl border border-slate-100 bg-white p-3.5" key={candidate.action}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-800">{label(candidate.action)}</p><p className="mt-1 text-xs leading-5 text-slate-500">{candidate.policy.reason}</p></div><div className="flex items-center gap-2"><Badge variant="outline" className={`text-[10px] ${candidate.policy.result === "approved" ? "border-teal-100 bg-teal-50 text-teal-700" : candidate.policy.result === "blocked" ? "border-rose-100 bg-rose-50 text-rose-700" : "border-amber-100 bg-amber-50 text-amber-800"}`}>{label(candidate.policy.result)}</Badge><Button size="sm" variant="outline" disabled={simulation.isPending} onClick={() => runSimulation(candidate.action)} className="rounded-lg border-slate-200">Simulate</Button></div></div><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">{candidate.policy.ruleCode}</p></div>)}</div></section>
      <aside className="space-y-5"><section className="rr-surface p-5"><div className="flex items-center gap-2"><Bot className="h-4 w-4 text-violet-600" /><div><p className="rr-eyebrow">Gemini analysis</p><h2 className="mt-1 text-lg font-semibold tracking-[-.04em] text-slate-950">Business-readable explanation</h2></div></div>{ai.error ? <div className="mt-4 rounded-xl border border-rose-100 bg-rose-50 p-4 text-sm text-rose-900"><CircleAlert className="h-4 w-4" /><p className="mt-2 font-bold">Gemini could not analyse this invoice.</p><p className="mt-1">{ai.error.message}</p></div> : ai.data ? <div className="mt-4 space-y-3"><div className="rounded-xl border border-violet-100 bg-violet-50/60 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-violet-700">Diagnosis</p><p className="mt-2 text-sm font-semibold text-violet-950">{ai.data.diagnosisSummary}</p><p className="mt-2 text-sm leading-6 text-slate-700">{ai.data.businessExplanation}</p></div><div className="rounded-xl border border-slate-200 bg-slate-50/80 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Risk note</p><p className="mt-2 text-sm leading-6 text-slate-800">{ai.data.riskNote}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Operator next step</p><p className="mt-2 text-sm font-semibold leading-6 text-slate-800">{ai.data.operatorNextStep}</p><p className="mt-3 text-xs text-slate-500">Policy rule: {ai.data.deterministicRecommendation.ruleCode}</p></div></div> : <div className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50 p-5 text-sm leading-6 text-slate-500">Generate an on-demand explanation of the overdue invoice. Gemini receives limited business context and cannot change a policy decision or initiate collection.</div>}</section>
        <section className="rr-surface p-5"><p className="rr-eyebrow">Promise-to-Pay</p><h2 className="mt-1 text-lg font-semibold tracking-[-.04em] text-slate-900">Record a future commitment</h2>{invoice.activePromise ? <div className={`mt-4 rounded-xl border p-3 ${invoice.activePromise.isMissed ? "border-rose-100 bg-rose-50 text-rose-900" : "border-teal-100 bg-teal-50 text-teal-900"}`}><p className="text-xs font-bold">{invoice.activePromise.isMissed ? "Missed promise detected" : "Active Promise-to-Pay"}</p><p className="mt-1 text-sm">{money(invoice.activePromise.promisedAmount)} due {date(invoice.activePromise.promisedDate)}</p></div> : <p className="mt-3 text-xs leading-5 text-slate-500">No active Promise-to-Pay is recorded.</p>}<div className="mt-4 grid gap-2 sm:grid-cols-2"><Input inputMode="decimal" value={promisedAmount} onChange={event => setPromisedAmount(event.target.value)} placeholder="Promised amount" className="h-10 rounded-lg" /><Input type="date" value={promisedDate} onChange={event => setPromisedDate(event.target.value)} className="h-10 rounded-lg" /></div><Button onClick={() => runSimulation("mark_promise_to_pay")} disabled={simulation.isPending || !Number(promisedAmount) || !promisedDate} variant="outline" className="mt-3 w-full rounded-lg border-violet-200 text-violet-800 hover:bg-violet-50">{simulation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <CalendarClock className="mr-2 h-4 w-4" />}Record simulated promise</Button><p className="mt-2 text-[11px] leading-5 text-slate-500">A Promise-to-Pay is only recorded after policy validation. It does not contact the customer or change a source invoice.</p></section></aside></div>
    {simulation.data ? <section className="rounded-2xl border border-teal-100 bg-teal-50 p-5"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-teal-700" /><div><p className="font-semibold text-teal-950">Simulation recorded: {label(simulation.data.simulation.executionStatus)}</p><p className="mt-1 text-sm leading-6 text-teal-900">{simulation.data.simulation.message}</p><p className="mt-2 text-xs font-semibold text-teal-800">{simulation.data.simulation.policy.ruleCode} · No real collection activity was performed.</p></div></div></section> : simulation.error ? <section className="rounded-2xl border border-rose-100 bg-rose-50 p-5 text-sm text-rose-900"><CircleAlert className="h-5 w-5" /><p className="mt-2 font-bold">The simulation could not be recorded.</p><p className="mt-1">{simulation.error.message}</p></section> : null}
    <div className="grid gap-5 xl:grid-cols-2"><section className="rr-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-slate-400" /><div><p className="rr-eyebrow">Promise timeline</p><h2 className="mt-1 text-xl font-semibold tracking-[-.04em] text-slate-950">Commitment history</h2></div></div><div className="mt-5 space-y-3">{detail.data.promises.length ? detail.data.promises.map(promise => <div key={promise.id} className={`rounded-xl border p-4 ${promise.isMissed ? "border-rose-100 bg-rose-50" : "border-slate-100 bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-800">{money(promise.promisedAmount)} by {date(promise.promisedDate)}</p><Badge variant="outline" className={promise.isMissed ? "border-rose-100 bg-rose-50 text-rose-700" : "border-teal-100 bg-teal-50 text-teal-700"}>{promise.isMissed ? "Missed" : label(promise.status)}</Badge></div>{promise.note ? <p className="mt-2 text-xs leading-5 text-slate-500">{promise.note}</p> : null}</div>) : <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No Promise-to-Pay commitments are recorded.</p>}</div></section><section className="rr-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Landmark className="h-5 w-5 text-slate-400" /><div><p className="rr-eyebrow">Invoice audit trail</p><h2 className="mt-1 text-xl font-semibold tracking-[-.04em] text-slate-950">Policy and simulated outcomes</h2></div></div><div className="mt-5 space-y-3">{detail.data.auditTimeline.length ? detail.data.auditTimeline.map(event => <div key={event.id} className="rounded-xl border border-slate-100 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-800">{label(event.action)}</p><Badge variant="outline" className="border-slate-200 bg-slate-50 text-slate-600">{label(event.executionResult ?? event.policyResult)}</Badge></div><p className="mt-2 text-xs leading-5 text-slate-500">{event.reason ?? "Receivables audit event recorded."}</p><p className="mt-2 text-[11px] font-semibold text-slate-400">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(event.timestamp))}</p></div>) : <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No invoice audit entries are available. A record is created only after an operator runs a simulation.</p>}</div></section></div>
  </div>;
}
