-- ReVora: PostgreSQL / Supabase schema recreation script
-- -----------------------------------------------------------------------------
-- Purpose: Documents and recreates the verified public tables in the existing
--          Supabase project. This file is NOT intended to be run against the
--          current ReVora Supabase database, which already contains tables
--          and data.
--
-- Source: Non-destructive PostgREST/OpenAPI inspection on 2026-08-27.
-- Notes: Column names, values, and nullable fields were verified. Primary keys,
--        relationships, checks, indexes, and RLS are safe design defaults for a
--        clean recreation; PostgREST inspection cannot prove every original
--        database-side constraint.
-- -----------------------------------------------------------------------------

begin;

create table if not exists public.payments (
  id integer generated by default as identity primary key,
  payment_id text not null unique,
  customer_id text not null,
  amount numeric(14, 2) not null check (amount >= 0),
  currency text not null default 'INR',
  payment_method text not null,
  gateway text not null,
  status text not null,
  failure_reason text,
  attempt_number integer not null default 1 check (attempt_number >= 1),
  previous_failures integer not null default 0 check (previous_failures >= 0),
  customer_success_history numeric(8, 6) check (customer_success_history between 0 and 1),
  timestamp timestamptz not null,
  merchant_category text,
  customer_tenure integer check (customer_tenure >= 0),
  device_type text,
  country text,
  hour_of_day integer check (hour_of_day between 0 and 23),
  is_recurring_payment boolean default false,
  days_since_last_success integer check (days_since_last_success >= 0),
  recoverable boolean,
  recovery_probability numeric(8, 6) check (recovery_probability between 0 and 1),
  recovery_status text,
  created_at timestamptz not null default now()
);

create table if not exists public.recovery_cases (
  id integer generated by default as identity primary key,
  payment_id text not null unique references public.payments(payment_id) on delete restrict,
  recovery_probability numeric(8, 6) check (recovery_probability between 0 and 1),
  ai_recommendation text,
  confidence numeric(8, 6) check (confidence between 0 and 1),
  case_status text not null,
  diagnosis text,
  reasoning text,
  created_at timestamptz not null default now(),
  reviewed_by text,
  human_decision text,
  reviewed_at timestamptz
);

create table if not exists public.recovery_actions (
  id integer generated by default as identity primary key,
  payment_id text not null references public.payments(payment_id) on delete restrict,
  action_type text not null,
  execution_status text not null,
  amount_recovered numeric(14, 2) not null default 0 check (amount_recovered >= 0),
  executed_at timestamptz,
  message text
);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  payment_id text not null references public.payments(payment_id) on delete restrict,
  ai_decision text,
  diagnosis text,
  recovery_probability numeric(8, 6) check (recovery_probability between 0 and 1),
  confidence numeric(8, 6) check (confidence between 0 and 1),
  policy_result text,
  action text,
  execution_result text,
  amount_recovered numeric(14, 2) not null default 0 check (amount_recovered >= 0),
  reason text,
  timestamp timestamptz not null default now()
);

-- Query patterns used by ReVora's dashboard, payment explorer, case view,
-- simulated execution history, and audit timeline.
create index if not exists payments_status_timestamp_idx
  on public.payments (status, timestamp desc);
create index if not exists payments_recovery_status_idx
  on public.payments (recovery_status);
create index if not exists payments_recovery_probability_idx
  on public.payments (recovery_probability desc);
create index if not exists payments_customer_id_idx
  on public.payments (customer_id);
create index if not exists recovery_cases_case_status_idx
  on public.recovery_cases (case_status, created_at desc);
create index if not exists recovery_actions_payment_executed_idx
  on public.recovery_actions (payment_id, executed_at desc);
create index if not exists audit_logs_payment_timestamp_idx
  on public.audit_logs (payment_id, timestamp asc);

-- Supabase security posture: the browser should not query these operational
-- tables directly. The ReVora server uses its service-role secret only on
-- the server side, where it can validate inputs and enforce policy rules.
alter table public.payments enable row level security;
alter table public.recovery_cases enable row level security;
alter table public.recovery_actions enable row level security;
alter table public.audit_logs enable row level security;

commit;
