-- ReVora: additive first-class policy-decision migration
-- -----------------------------------------------------------------------------
-- Purpose: create an immutable policy_decisions ledger for simulated recovery
--          decisions. This migration is additive: it does not alter, delete, or
--          reseed existing payments, recovery cases, recovery actions, or audits.
--
-- Apply manually in the active project's Supabase SQL Editor only after review.
-- Do not run against a populated database if a table named policy_decisions
-- already exists with a different schema.
-- -----------------------------------------------------------------------------

begin;

create table if not exists public.policy_decisions (
  id integer generated by default as identity primary key,
  payment_id text not null references public.payments(payment_id) on delete restrict,
  recovery_case_id integer references public.recovery_cases(id) on delete set null,
  recovery_action_id integer references public.recovery_actions(id) on delete set null,
  action text not null check (action in (
    'retry_payment',
    'send_recovery_reminder',
    'suggest_alternate_payment',
    'escalate_to_human',
    'do_nothing'
  )),
  policy_result text not null check (policy_result in (
    'APPROVED',
    'BLOCKED',
    'HUMAN_REVIEW_REQUIRED'
  )),
  rule_code text not null,
  reason text not null,
  recovery_probability numeric(8, 6) check (recovery_probability between 0 and 1),
  attempt_number integer check (attempt_number >= 1),
  autopilot_limit_amount numeric(14, 2) not null default 5000 check (autopilot_limit_amount >= 0),
  policy_version text not null default 'recoverai-v1',
  actor text not null default 'policy_engine',
  simulation_only boolean not null default true check (simulation_only = true),
  decision_timestamp timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists policy_decisions_payment_timestamp_idx
  on public.policy_decisions (payment_id, decision_timestamp desc);
create index if not exists policy_decisions_result_timestamp_idx
  on public.policy_decisions (policy_result, decision_timestamp desc);
create index if not exists policy_decisions_case_idx
  on public.policy_decisions (recovery_case_id);

-- The operational UI calls the ReVora server only. The server's service-role
-- key remains private and is the only process permitted to write this ledger.
alter table public.policy_decisions enable row level security;

-- Preserve policy decisions as an append-only ledger. Corrections must be new
-- decision rows, never updates or deletes of historical decisions.
create or replace function public.prevent_policy_decision_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'policy_decisions is append-only; create a new decision record instead of changing history';
end;
$$;

drop trigger if exists policy_decisions_append_only on public.policy_decisions;
create trigger policy_decisions_append_only
before update or delete on public.policy_decisions
for each row execute function public.prevent_policy_decision_mutation();

commit;

-- Post-apply verification (run separately in Supabase SQL Editor):
-- select column_name, data_type, is_nullable
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'policy_decisions'
-- order by ordinal_position;
--
-- select indexname from pg_indexes
-- where schemaname = 'public' and tablename = 'policy_decisions';
