-- ReVora B2B Receivables Recovery extension
-- -----------------------------------------------------------------------------
-- MANUAL HANDOFF ONLY: review and run this once in the Supabase SQL Editor for
-- the intended ReVora project. It creates no invoice data and does not alter
-- existing payment, policy_decisions, recovery_actions, or audit_logs records.

begin;

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_id text not null unique,
  customer_id text not null,
  customer_name text,
  amount numeric(14, 2) not null check (amount >= 0),
  currency text not null default 'INR',
  issued_date date not null,
  due_date date not null,
  status text not null default 'open' check (status in ('draft', 'open', 'partially_paid', 'paid', 'written_off', 'disputed', 'cancelled')),
  payment_terms_days integer check (payment_terms_days >= 0),
  payment_reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (due_date >= issued_date)
);

create table if not exists public.invoice_promises (
  id bigint generated by default as identity primary key,
  invoice_id text not null references public.invoices(invoice_id) on delete restrict,
  promised_amount numeric(14, 2) not null check (promised_amount > 0),
  promised_date date not null,
  status text not null default 'active' check (status in ('active', 'kept', 'missed', 'cancelled')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_policy_decisions (
  id bigint generated by default as identity primary key,
  invoice_id text not null references public.invoices(invoice_id) on delete restrict,
  action text not null check (action in ('send_reminder', 'follow_up', 'escalate', 'mark_promise_to_pay', 'do_nothing')),
  policy_result text not null check (policy_result in ('APPROVED', 'BLOCKED', 'HUMAN_REVIEW_REQUIRED')),
  rule_code text not null,
  reason text not null,
  recovery_probability numeric(8, 6) not null check (recovery_probability between 0 and 1),
  outstanding_amount numeric(14, 2) not null check (outstanding_amount >= 0),
  policy_version text not null default 'recoverai-invoice-v1',
  actor text not null default 'invoice_policy_engine',
  simulation_only boolean not null default true,
  decision_timestamp timestamptz not null default now()
);

create table if not exists public.invoice_recovery_actions (
  id bigint generated by default as identity primary key,
  invoice_id text not null references public.invoices(invoice_id) on delete restrict,
  action_type text not null check (action_type in ('send_reminder', 'follow_up', 'escalate', 'mark_promise_to_pay', 'do_nothing')),
  execution_status text not null check (execution_status in ('SUCCESS', 'FAILED', 'BLOCKED', 'ESCALATED', 'SKIPPED')),
  amount_recovered numeric(14, 2) not null default 0 check (amount_recovered >= 0),
  executed_at timestamptz not null default now(),
  message text not null
);

create table if not exists public.invoice_audit_logs (
  id bigint generated by default as identity primary key,
  invoice_id text not null references public.invoices(invoice_id) on delete restrict,
  ai_decision text,
  diagnosis text,
  recovery_probability numeric(8, 6) check (recovery_probability between 0 and 1),
  policy_result text,
  action text,
  execution_result text,
  amount_recovered numeric(14, 2) not null default 0 check (amount_recovered >= 0),
  reason text,
  timestamp timestamptz not null default now()
);

create index if not exists invoices_status_due_date_idx on public.invoices (status, due_date asc);
create index if not exists invoices_customer_id_idx on public.invoices (customer_id);
create index if not exists invoice_promises_invoice_status_date_idx on public.invoice_promises (invoice_id, status, promised_date asc);
create index if not exists invoice_policy_decisions_invoice_timestamp_idx on public.invoice_policy_decisions (invoice_id, decision_timestamp desc);
create index if not exists invoice_recovery_actions_invoice_executed_idx on public.invoice_recovery_actions (invoice_id, executed_at desc);
create index if not exists invoice_audit_logs_invoice_timestamp_idx on public.invoice_audit_logs (invoice_id, timestamp desc);

alter table public.invoices enable row level security;
alter table public.invoice_promises enable row level security;
alter table public.invoice_policy_decisions enable row level security;
alter table public.invoice_recovery_actions enable row level security;
alter table public.invoice_audit_logs enable row level security;

commit;
